### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by imgustavo** [ItzLevvie/Agario-skins#8]
Hi Levvie, i was wondering do you know any way to get to know the ip connected to an specific server of agar.io? I heard some people know about this and im sure exist a way. As u know all mods moderns like: delta, legend mode, etc are from the same root: ogar mod, and i think its something related about this u can get that information. I remember in ogar was a command when u create your own private server, was: "playerlist" u put that in console and u could see all list of players and their ips. I was wondering do u know how to get that information?

**Comment by ItzLevvie** [comment]
If you want to know what Agar.io server you are connected to: you can find that out by doing F12 -> Network.

If you want to know people's IP addresses without being a Server Owner: you can not do that as all Agar.io servers, including private servers, are all Dedicated Servers and not Peer-to-Peer.
